### ISSUE TITLE
error import

### ISSUE THREAD

**Issue by saibai** [ReshotAI/gaussian-splatting-blender-addon#11]
I can't import ply files, it always gives me this error, on Blender 6.5.1 and MacBookPro M2

Python: Traceback (most recent call last):
  File "/Library/Application Support/Blender/3.6/scripts/addons/blender-addon/__init__.py", line 66, in execute
    log_opacities = np.asarray(plydata.elements[0]["opacity"])[..., np.newaxis]
  File "Library/Application Support/Blender/3.6/scripts/addons/blender-addon/plyfile.py", line 715, in __getitem__
    return self.data[key]
ValueError: no field of name opacity

how can I solve it?
Grazie

**Comment by Iron-LYK** [comment]
same error, have you solved it yet?
