### ISSUE TITLE
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'

### ISSUE THREAD

**Issue by manuel-masiello** [ReshotAI/gaussian-splatting-blender-addon#16]
Hello,
Thank you for your work. 

I'm on Ubuntu with Blender 4.0.x and I get the following error during import.
It seems that pullrequests can provide a solution even if these errors are not in the discussion of pullrequests.

```
Read prefs: "/home/me/.config/blender/4.0/config/userpref.blend"
Info: Deleted 3 object(s)

PLY loaded in 0.0033948421478271484 seconds
Data loaded in 1.073183536529541 seconds
Mesh loaded in 0.3035547733306885 seconds
Mesh attributes added in 1.1825714111328125 seconds
Traceback (most recent call last):
  File "/home/me/.config/blender/4.0/scripts/addons/blender-addon/__init__.py", line 239, in execute
    principled_node.inputs["Specular"].default_value = 0
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
Traceback (most recent call last):
  File "/home/me/.config/blender/4.0/scripts/addons/blender-addon/__init__.py", line 1133, in draw
    row.prop(obj.modifiers["GeometryNodes"].node_group.nodes.get("Boolean"), "boolean", text="As point cloud (faster)")
KeyError: 'bpy_prop_collection[key]: key "GeometryNodes" not found'

```

**Comment by Wladefant** [comment]
try to download the latest version it should be fixed for blender 4.0

**Comment by JuanRamirezJorda** [comment]
Do you have any new on this? I got this error: 

Error importing: C:\Users\juano\OneDrive\Desktop\Proyecto_Prueba\new_com3_837royal.ydr.xml 
 Traceback (most recent call last):
  File "C:\Users\juano\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz_rdr3-main\sollumz_operators.py", line 65, in import_file
    import_ydr(filepath, self.import_settings)
  File "C:\Users\juano\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz_rdr3-main\ydr\ydrimport.py", line 624, in import_ydr
    drawable = drawable_to_obj(ydr_xml, filepath, os.path.basename(
  File "C:\Users\juano\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz_rdr3-main\ydr\ydrimport.py", line 540, in drawable_to_obj
    materials = shadergroup_to_materials(drawable.shader_group, filepath)
  File "C:\Users\juano\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz_rdr3-main\ydr\ydrimport.py", line 21, in shadergroup_to_materials
    material = create_shader(shader.name, shader.filename)
  File "C:\Users\juano\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz_rdr3-main\ydr\shader_materials.py", line 734, in create_shader
    create_basic_shader_nodes(mat, shader, filename)
  File "C:\Users\juano\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz_rdr3-main\ydr\shader_materials.py", line 592, in create_basic_shader_nodes
    link_specular(node_tree, spectex)
  File "C:\Users\juano\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Sollumz_rdr3-main\ydr\shader_materials.py", line 345, in link_specular
    links.new(spctex.outputs["Color"], bsdf.inputs["Specular"])
KeyError: 'bpy_prop_collection[key]: key "Specular" not found'
