### ISSUE TITLE
Error when importing ply

### ISSUE THREAD

**Issue by joebain** [ReshotAI/gaussian-splatting-blender-addon#2]
Hi, first I want to say thanks for publishing this addon, it looks super useful. I'm trying to import a ply from the polycam gaussian splatting app however I get an error when I do. I'm using blender 3.6.4 on Mac OS.

```
bpy.context.space_data.system_bookmarks_active = 3
Python: Traceback (most recent call last):
  File "/Users/joe/Library/Application Support/Blender/3.6/scripts/addons/blender-addon/__init__.py", line 229, in execute
    opacity_geom_attr_node.outputs["Value"],
KeyError: 'bpy_prop_collection[key]: key "Value" not found'
bpy.ops.object.import_gaussian_splatting(filepath="/Users/joe/Downloads/toy-village-splat.ply")
Python: Traceback (most recent call last):
  File "/Users/joe/Library/Application Support/Blender/3.6/scripts/addons/blender-addon/__init__.py", line 1135, in draw
    row.prop(obj.modifiers["GeometryNodes"].node_group.nodes.get("Boolean"), "boolean", text="As point cloud (faster)")
KeyError: 'bpy_prop_collection[key]: key "GeometryNodes" not found'
Python: Traceback (most recent call last):
  File "/Users/joe/Library/Application Support/Blender/3.6/scripts/addons/blender-addon/__init__.py", line 1135, in draw
    row.prop(obj.modifiers["GeometryNodes"].node_group.nodes.get("Boolean"), "boolean", text="As point cloud (faster)")
KeyError: 'bpy_prop_collection[key]: key "GeometryNodes" not found'
Python: Traceback (most recent call last):
  File "/Users/joe/Library/Application Support/Blender/3.6/scripts/addons/blender-addon/__init__.py", line 1135, in draw
    row.prop(obj.modifiers["GeometryNodes"].node_group.nodes.get("Boolean"), "boolean", text="As point cloud (faster)")
KeyError: 'bpy_prop_collection[key]: key "GeometryNodes" not found'
Python: Traceback (most recent call last):
  File "/Users/joe/Library/Application Support/Blender/3.6/scripts/addons/blender-addon/__init__.py", line 1135, in draw
    row.prop(obj.modifiers["GeometryNodes"].node_group.nodes.get("Boolean"), "boolean", text="As point cloud (faster)")
KeyError: 'bpy_prop_collection[key]: key "GeometryNodes" not found'
Python: Traceback (most recent call last):
  File "/Users/joe/Library/Application Support/Blender/3.6/scripts/addons/blender-addon/__init__.py", line 1135, in draw
    row.prop(obj.modifiers["GeometryNodes"].node_group.nodes.get("Boolean"), "boolean", text="As point cloud (faster)")
KeyError: 'bpy_prop_collection[key]: key "GeometryNodes" not found'
Python: Traceback (most recent call last):
  File "/Users/joe/Library/Application Support/Blender/3.6/scripts/addons/blender-addon/__init__.py", line 1135, in draw
    row.prop(obj.modifiers["GeometryNodes"].node_group.nodes.get("Boolean"), "boolean", text="As point cloud (faster)")
KeyError: 'bpy_prop_collection[key]: key "GeometryNodes" not found'
Python: Traceback (most recent call last):
  File "/Users/joe/Library/Application Support/Blender/3.6/scripts/addons/blender-addon/__init__.py", line 1135, in draw
    row.prop(obj.modifiers["GeometryNodes"].node_group.nodes.get("Boolean"), "boolean", text="As point cloud (faster)")
KeyError: 'bpy_prop_collection[key]: key "GeometryNodes" not found'
```

If you are able to give me any help I'd really appreciate it. I'm not very familiar with blender scripting unfortunately otherwise I'd try to fix this myself.

**Comment by alexandre01** [comment]
Thanks for trying! I tested the add-on on Linux only, it seems the "GeometryNodes" key has a different name on MacOs / Windows. Will work on this hopefully this evening!

**Comment by alexandre01** [comment]
Should be fixed

**Comment by glaciate-ruby-antelope** [comment]
It does work on mac now.

THANKS!

**Comment by Ednaordinary** [comment]
Thanks for trying! I tested the addon on Linux only, it seems the "GeometryNodes" key has a different name on macOS / Windows. I will work on this hopefully this evening!

Doesn't seem to be OS dependent, I had the same error before fixing it on my own install (I thought it might be a version issue, I'm on Blender 3.6.0, Linux).

**Comment by alexandre01** [comment]
Yes yes it was due to something I had forgotten to push. Seems you found the 2/3 lines to edit to fix it
