### ISSUE TITLE
import Error

### ISSUE THREAD

**Issue by Lindsaydoodle** [ReshotAI/gaussian-splatting-blender-addon#25]
Blender 3.6.8
Python: Traceback (most recent call last):
  File "C:\Users\lind\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-addon\__init__.py", line 74, in execute
    features_dc[:, 0, 0] = np.asarray(plydata.elements[0]["f_dc_0"])
  File "C:\Users\lind\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\blender-addon\plyfile.py", line 715, in __getitem__
    return self.data[key]
  File "M:\SteamLibrary\steamapps\common\Blender\3.6\python\lib\site-packages\numpy\core\memmap.py", line 334, in __getitem__
    res = super().__getitem__(index)
ValueError: no field of name f_dc_0

Bleder 4.1.0 and 4.0.2 same
Python: Traceback (most recent call last):
  File "C:\Users\lind\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-addon\__init__.py", line 74, in execute
    features_dc[:, 0, 0] = np.asarray(plydata.elements[0]["f_dc_0"])
                                      ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\lind\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-addon\plyfile.py", line 715, in __getitem__
    return self.data[key]
           ~~~~~~~~~^^^^^
  File "S:\blender-4.1.0-alpha+main.da77f90744c1-windows.amd64-release\4.1\python\Lib\site-packages\numpy\core\memmap.py", line 334, in __getitem__
    res = super().__getitem__(index)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: no field of name f_dc_0

**Comment by IgorVe** [comment]
same issue plz help

**Comment by IgorVe** [comment]
Solved. It was wrong version of the addon, you can fond info here https://github.com/ReshotAI/gaussian-splatting-blender-addon/pull/24/files

But dear ReshotAI, could you name your projects properly plz to avoid misunderstandings in future? Thank you!

**Comment by 4v4v4v4v4** [comment]
I am still receiving this error:

Python: Traceback (most recent call last):
  File "C:\Users\aclifforth\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-addon\__init__.py", line 74, in execute
    features_dc[:, 0, 0] = np.asarray(plydata.elements[0]["f_dc_0"])
                                      ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\aclifforth\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-addon\plyfile.py", line 715, in __getitem__
    return self.data[key]
           ~~~~~~~~~^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\site-packages\numpy\core\memmap.py", line 334, in __getitem__
    res = super().__getitem__(index)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: no field of name f_dc_0

I have tried on Blender 4.0 and Blender 4.1 with the updated script. Still no luck! Please help!

**Comment by kusstox** [comment]
> I am still receiving this error:
> 
> Python: Traceback (most recent call last): File "C:\Users\aclifforth\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-addon__init__.py", line 74, in execute features_dc[:, 0, 0] = np.asarray(plydata.elements[0]["f_dc_0"]) ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^ File "C:\Users\aclifforth\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\blender-addon\plyfile.py", line 715, in **getitem** return self.data[key] ~~~~~~~~~^^^^^ File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\site-packages\numpy\core\memmap.py", line 334, in **getitem** res = super().**getitem**(index) ^^^^^^^^^^^^^^^^^^^^^^^^^^ ValueError: no field of name f_dc_0
> 
> I have tried on Blender 4.0 and Blender 4.1 with the updated script. Still no luck! Please help!

Same issue, have you solved it?
