### ISSUE TITLE
ValueError: no field of name f_dc_0 

### ISSUE THREAD

**Issue by caiolopesdasilva** [ReshotAI/gaussian-splatting-blender-addon#42]
Hi all,

I tried to using this addon in multiple versions of Blender, from 3.6LTS to 4.0 4.1 and 4.2

I always face the same error:

```
Python: Traceback (most recent call last):
  File "C:\Users\render\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\gaussian_splatting_io\__init__.py", line 74, in execute
    features_dc[:, 0, 0] = np.asarray(plydata.elements[0]["f_dc_0"])
                                      ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\render\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\gaussian_splatting_io\plyfile.py", line 715, in __getitem__
    return self.data[key]
           ~~~~~~~~~^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\site-packages\numpy\core\memmap.py", line 334, in __getitem__
    res = super().__getitem__(index)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: no field of name f_dc_0
```

I see others are facing the same issue but I have not found a proper solution for this. I am using the latest version from this repo. Anything that I can do?

**Comment by juliette1ternet** [comment]
Hi,

I faced the same issue on different versions as well,
It stopped giving me the error when I imported a .splat instead of a .ply. I hope this will help!

**Comment by errorsurface** [comment]
I was getting the same error with this add-on as well with the Kiri Engine one. 
If you are using Polycam download the SPLAT .ply, instead of the regular one.

**Comment by NotCompsky** [comment]
> I faced the same issue on different versions as well, It stopped giving me the error when I imported a .splat instead of a .ply. I hope this will help!

I still get the problem even when converting a problematic `.ply` file into a `.splat` by using SuperSplat. So I don't think the `.ply` parser is the problem.

**Comment by Sarah-C** [comment]
I've made a fix, to use default values for those when the PLY file is imported, because it doesn't contain those parameters.

https://github.com/ReshotAI/gaussian-splatting-blender-addon/issues/44
