### ISSUE TITLE
Error - Blender

### ISSUE THREAD

**Issue by Fanie-Visagie** [ReshotAI/gaussian-splatting-blender-addon#8]
Not sure why I get this...

Python: Traceback (most recent call last):
  File "C:\Users\perso\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-addon\plyfile.py", line 160, in read
    data = PlyData._parse_header(stream)
  File "C:\Users\perso\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-addon\plyfile.py", line 121, in _parse_header
    parser = _PlyHeaderParser(_PlyHeaderLines(stream))
  File "C:\Users\perso\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blender-addon\plyfile.py", line 1270, in __init__
    raise PlyHeaderParseError("expected 'ply'", 1)
blender-addon.plyfile.PlyHeaderParseError: line 1: expected 'ply'

importing a splat file called vessel.splat and using Blender 4.0 ??

Appreciate being pointed in the right direction ... (",)

**Comment by Fanie-Visagie** [comment]
Thanks mate. Much appreciated and thanks. It works great. Blender 4 is bringing the point clouds hard.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
